import Zcash.Snark.ZeroKnowledge.Randomness

/-!
# Uniform digest preimages of a wide-reduced field challenge

An oracle simulator must return a 512-bit digest whose reduction is its chosen
field challenge. The preimages are exactly `field.val + p * quotient`, with
`Q + 1` possible quotients on the heavy residues and `Q` otherwise. This gives
a direct bounded-integer sampler rather than searching the whole digest space.
-/

namespace Zcash.Snark.ZeroKnowledge

set_option exponentiation.threshold 1024
set_option maxRecDepth 8192

open Zcash.Arithmetic (Fp scalarFieldOrder)
open scoped ENNReal

/-- The number of digests reducing to a given field value. -/
def digestFiberSize (field : Fp) : ℕ :=
  challengeQuot + if field.val < challengeRem then 1 else 0

/-- Every field challenge has at least one digest preimage. -/
theorem digestFiberSize_pos (field : Fp) : 0 < digestFiberSize field := by
  have hq : 0 < challengeQuot := by decide
  unfold digestFiberSize
  omega

/-- Each allowed quotient gives a digest in the specified 512-bit range. -/
theorem digestFromQuotient_lt (field : Fp) (quotient : Fin (digestFiberSize field)) :
    field.val + scalarFieldOrder * quotient.val < challengeDigestCard := by
  have hp := ZMod.val_lt field
  have hdiv : scalarFieldOrder * challengeQuot + challengeRem = challengeDigestCard :=
    Nat.div_add_mod challengeDigestCard scalarFieldOrder
  by_cases hf : field.val < challengeRem
  · have hq : quotient.val < challengeQuot + 1 := calc
      _ < digestFiberSize field := quotient.isLt
      _ = challengeQuot + 1 := by simp only [digestFiberSize, if_pos hf]
    have hmul := Nat.mul_le_mul_left scalarFieldOrder (show quotient.val ≤ challengeQuot by omega)
    omega
  · have hq : quotient.val < challengeQuot := calc
      _ < digestFiberSize field := quotient.isLt
      _ = challengeQuot := by simp only [digestFiberSize, if_neg hf, Nat.add_zero]
    have hmul := Nat.mul_le_mul_left scalarFieldOrder (show quotient.val + 1 ≤ challengeQuot by omega)
    rw [Nat.mul_add, Nat.mul_one] at hmul
    omega

/-- A direct digest constructor using a field value and one bounded quotient. -/
def digestFromQuotient (field : Fp) (quotient : Fin (digestFiberSize field)) : Fin challengeDigestCard :=
  ⟨field.val + scalarFieldOrder * quotient.val, digestFromQuotient_lt field quotient⟩

/-- Every constructed digest reduces to the requested field challenge. -/
theorem digestFromQuotient_reduce (field : Fp) (quotient : Fin (digestFiberSize field)) :
    ((digestFromQuotient field quotient).val : Fp) = field := by
  change ((field.val + scalarFieldOrder * quotient.val : ℕ) : ZMod scalarFieldOrder) = field
  simp only [Nat.cast_add, Nat.cast_mul, ZMod.natCast_zmod_val, ZMod.natCast_self, zero_mul, add_zero]

/-- Distinct quotients give distinct raw digests. -/
theorem digestFromQuotient_injective (field : Fp) : Function.Injective (digestFromQuotient field) := by
  intro left right h
  have hv := congrArg Fin.val h
  change field.val + scalarFieldOrder * left.val = field.val + scalarFieldOrder * right.val at hv
  apply Fin.ext
  exact (mul_left_cancel₀ (NeZero.ne scalarFieldOrder)) (Nat.add_left_cancel hv)

/-- Reduction identifies exactly the digests generated by the allowed quotients. -/
theorem digestFromQuotient_range (field : Fp) (digest : Fin challengeDigestCard) :
    (digest.val : Fp) = field ↔ ∃ quotient, digestFromQuotient field quotient = digest := by
  constructor
  · intro h
    have hmod : digest.val % scalarFieldOrder = field.val := by
      simpa only [ZMod.val_natCast] using congrArg ZMod.val h
    have hrepr : field.val + scalarFieldOrder * (digest.val / scalarFieldOrder) = digest.val := by
      rw [← hmod]
      exact Nat.mod_add_div _ _
    have hdiv : scalarFieldOrder * challengeQuot + challengeRem = challengeDigestCard :=
      Nat.div_add_mod challengeDigestCard scalarFieldOrder
    have hrem : challengeRem < scalarFieldOrder := Nat.mod_lt _ (Nat.pos_of_ne_zero (NeZero.ne _))
    have hq : digest.val / scalarFieldOrder < digestFiberSize field := by
      unfold digestFiberSize
      by_cases hf : field.val < challengeRem
      · rw [if_pos hf]
        by_contra hn
        have hm := Nat.mul_le_mul_left scalarFieldOrder (Nat.le_of_not_gt hn)
        rw [Nat.mul_add, Nat.mul_one] at hm
        have hd := digest.isLt
        omega
      · rw [if_neg hf, Nat.add_zero]
        by_contra hn
        have hm := Nat.mul_le_mul_left scalarFieldOrder (Nat.le_of_not_gt hn)
        have hd := digest.isLt
        omega
    exact ⟨⟨digest.val / scalarFieldOrder, hq⟩, Fin.ext hrepr⟩
  · rintro ⟨quotient, rfl⟩
    exact digestFromQuotient_reduce field quotient

/-- Uniformly sample the allowed quotient, then construct its raw digest. -/
noncomputable def digestFiberSample (field : Fp) : PMF (Fin challengeDigestCard) := by
  letI : NeZero (digestFiberSize field) := ⟨(digestFiberSize_pos field).ne'⟩
  exact (PMF.uniformOfFintype (Fin (digestFiberSize field))).map (digestFromQuotient field)

/-- The direct sampler is uniform on exactly the requested reduction fiber. -/
theorem digestFiberSample_apply (field : Fp) (digest : Fin challengeDigestCard) :
    digestFiberSample field digest =
      if (digest.val : Fp) = field then (digestFiberSize field : ℝ≥0∞)⁻¹ else 0 := by
  classical
  rw [digestFiberSample, PMF.map_apply]
  by_cases hd : (digest.val : Fp) = field
  · obtain ⟨quotient, rfl⟩ := (digestFromQuotient_range field digest).mp hd
    simp only [digestFromQuotient_reduce, if_true,
      (digestFromQuotient_injective field).eq_iff, PMF.uniformOfFintype_apply, Fintype.card_fin]
    simpa only [eq_comm] using
      (tsum_ite_eq quotient (fun _ => (digestFiberSize field : ℝ≥0∞)⁻¹))
  · rw [if_neg hd]
    apply ENNReal.tsum_eq_zero.mpr
    intro quotient
    have hn : digest ≠ digestFromQuotient field quotient := by
      intro h
      exact hd (h ▸ digestFromQuotient_reduce field quotient)
    exact if_neg hn

/-- Wide-reduction mass times its conditional digest mass is the original uniform digest mass. -/
theorem fieldSample_mul_digestFiberSample (field : Fp) (digest : Fin challengeDigestCard) :
    fieldSample field * digestFiberSample field digest =
      if (digest.val : Fp) = field then (challengeDigestCard : ℝ≥0∞)⁻¹ else 0 := by
  rw [fieldSample_apply, digestFiberSample_apply]
  change ((digestFiberSize field : ℝ≥0∞) / challengeDigestCard) *
    (if (digest.val : Fp) = field then (digestFiberSize field : ℝ≥0∞)⁻¹ else 0) = _
  by_cases hd : (digest.val : Fp) = field
  · rw [if_pos hd, if_pos hd, div_eq_mul_inv, mul_right_comm,
      ENNReal.mul_inv_cancel (Nat.cast_ne_zero.mpr (digestFiberSize_pos field).ne')
        (ENNReal.natCast_ne_top _), one_mul]
  · simp only [if_neg hd, mul_zero]

end Zcash.Snark.ZeroKnowledge
