import Zcash.Snark.ZeroKnowledge.IpaTranscript
import Zcash.Snark.ZeroKnowledge.CommitmentMask

/-!
# Joint simulation of the sparse-mask IPA stage

For fixed public challenges with `xi ≠ 0` and nonzero folding challenges, the simulator
reproduces the entire algebraic transcript: the mask commitment, every left/right message,
the final scalar `c`, and the aggregate blind `f`.

The field masks and blinds are ideal uniform samples. The group is a finite cyclic
`F`-module generated by `W`, expressed by bijectivity of `r ↦ r • W`. Its inverse is used
only in a probability-preserving change of variables, never by the simulator. This is
not a theorem about Fiat–Shamir challenge generation, retry-conditioned executions, or
the preceding PLONK and multi-opening messages.
-/

namespace Zcash.Snark.ZeroKnowledge

variable {F G : Type*} [Field F] [AddCommGroup G] [Module F G]

/-- All independently blinded left/right points are reparameterized simultaneously. -/
noncomputable def ipaMessageBlindsEquiv {k : ℕ} (W : G) (messages : Fin k → G × G)
    (hW : Function.Bijective (fun r : F => r • W)) :
    (Fin k → F × F) ≃ (Fin k → G × G) :=
  Equiv.piCongrRight fun j =>
    Equiv.prodCongr (blindPointEquiv W (messages j).1 hW)
      (blindPointEquiv W (messages j).2 hW)

/-- Replacing the mask-commitment blind by the actually accumulated `f` is reversible. -/
def ipaAccumulatorEquiv {k : ℕ} (rho xi : F) (rounds : Fin k → F) (hxi : xi ≠ 0) :
    IpaBlinds k F ≃ IpaBlinds k F where
  toFun := fun blinds => (ipaFinalBlind rho xi rounds blinds, blinds.2)
  invFun := fun values =>
    ((values.1 - rho -
      ∑ j, ((rounds j)⁻¹ * (values.2 j).1 + rounds j * (values.2 j).2)) / xi, values.2)
  left_inv := by
    intro blinds
    apply Prod.ext
    · simp only [ipaFinalBlind]
      field_simp
      ring
    · rfl
  right_inv := by
    intro values
    apply Prod.ext
    · simp only [ipaFinalBlind]
      field_simp
      ring
    · rfl

/-- Private blinds are in bijection with all round messages together with the final blind. -/
noncomputable def ipaBlindsEquiv {k : ℕ} (W : G) (messages : Fin k → G × G)
    (rho xi : F) (rounds : Fin k → F)
    (hW : Function.Bijective (fun r : F => r • W)) (hxi : xi ≠ 0) :
    IpaBlinds k F ≃ ((Fin k → G × G) × F) :=
  (ipaAccumulatorEquiv rho xi rounds hxi).trans
    ((Equiv.prodCongr (Equiv.refl F) (ipaMessageBlindsEquiv W messages hW)).trans
      (Equiv.prodComm F (Fin k → G × G)))

/-- The forward change of variables is exactly the honest messages and honest `f`. -/
theorem ipaBlindsEquiv_apply {k : ℕ} (W : G) (messages : Fin k → G × G)
    (rho xi : F) (rounds : Fin k → F)
    (hW : Function.Bijective (fun r : F => r • W)) (hxi : xi ≠ 0)
    (blinds : IpaBlinds k F) :
    ipaBlindsEquiv W messages rho xi rounds hW hxi blinds =
      (blindIpaMessages W messages blinds.2, ipaFinalBlind rho xi rounds blinds) := rfl

section Distributions

variable [Fintype F] [Fintype G]

/-- The honest raw IPA transcript with ideal independent field masks and commitment blinds. -/
noncomputable def idealIpaProver {k : ℕ} (pub : IpaPublic k F G)
    (coefficients : Fin (2 ^ k) → F) (rho : F) : PMF (IpaTranscript k F G) :=
  (PMF.uniformOfFintype (Fin k → F)).bind fun alphas =>
    (PMF.uniformOfFintype (IpaBlinds k F)).map
      (honestIpaTranscript pub coefficients rho alphas)

/-- The simulator knows only public data; its scalar law selects the public-zero case. -/
noncomputable def idealIpaSimulator {k : ℕ} (pub : IpaPublic k F G) : PMF (IpaTranscript k F G) :=
  (PMF.uniformOfFintype ((Fin k → G × G) × F)).bind fun free =>
    (idealSparseIpaScalar pub.point pub.rounds).map fun c =>
      completeIpaTranscript pub free.1 c free.2

/-- With any fixed sparse mask, independently uniform blinds make the round messages and `f`
jointly uniform. The remaining commitment is fixed by the verified equation. -/
theorem honestIpaTranscript_fixed_mask {k : ℕ} (pub : IpaPublic k F G)
    (coefficients : Fin (2 ^ k) → F) (rho : F) (alphas : Fin k → F)
    (hW : Function.Bijective (fun r : F => r • pub.W)) (hxi : pub.xi ≠ 0)
    (hcommit : pub.commitment = commitGen pub.generators coefficients + rho • pub.W)
    (hv : coefficientEvaluation k pub.point coefficients = pub.value)
    (hu : ∀ j, pub.rounds j ≠ 0) :
    (PMF.uniformOfFintype (IpaBlinds k F)).map
        (honestIpaTranscript pub coefficients rho alphas) =
      (PMF.uniformOfFintype ((Fin k → G × G) × F)).map fun free =>
        completeIpaTranscript pub free.1
          (maskedIpaScalar pub.point pub.xi pub.value pub.rounds coefficients alphas) free.2 := by
  let e := ipaBlindsEquiv pub.W
    (ipaCoreMessages pub.z pub.U k pub.rounds (ipaMaskedVector pub coefficients alphas)
      (evalVector k pub.point) pub.generators) rho pub.xi pub.rounds hW hxi
  let finish := fun free : (Fin k → G × G) × F =>
    completeIpaTranscript pub free.1
      (maskedIpaScalar pub.point pub.xi pub.value pub.rounds coefficients alphas) free.2
  have hfactor : honestIpaTranscript pub coefficients rho alphas = finish ∘ e := by
    funext blinds
    exact IpaTranscript.eq_complete_of_verifies pub
      (honestIpaTranscript pub coefficients rho alphas blinds) hxi
      (honestIpaTranscript_verifies pub coefficients rho alphas blinds hcommit hv hu)
  rw [hfactor, ← PMF.map_comp, Zcash.map_uniformOfFintype_equiv]

/-- Exact joint simulation of the algebraic IPA stage under ideal field randomness.

The theorem quantifies over every valid opening of the same public commitment and evaluation.
The simulator has no witness input and does not compute discrete logarithms. Encoding failures,
zero challenges, the actual sampling bias and Fiat–Shamir composition are separate obligations. -/
theorem idealIpa_simulation_capstone {k : ℕ} (pub : IpaPublic k F G)
    (coefficients : Fin (2 ^ k) → F) (rho : F)
    (hW : Function.Bijective (fun r : F => r • pub.W)) (hxi : pub.xi ≠ 0)
    (hcommit : pub.commitment = commitGen pub.generators coefficients + rho • pub.W)
    (hv : coefficientEvaluation k pub.point coefficients = pub.value)
    (hu : ∀ j, pub.rounds j ≠ 0) :
    idealIpaProver pub coefficients rho = idealIpaSimulator pub := by
  unfold idealIpaProver idealIpaSimulator
  simp_rw [honestIpaTranscript_fixed_mask pub coefficients rho _ hW hxi hcommit hv hu]
  simp only [PMF.map, Function.comp_def]
  rw [PMF.bind_comm]
  congr 1
  funext free
  change (PMF.uniformOfFintype (Fin k → F)).map
      (fun alphas => completeIpaTranscript pub free.1
        (maskedIpaScalar pub.point pub.xi pub.value pub.rounds coefficients alphas) free.2) =
    (idealSparseIpaScalar pub.point pub.rounds).map
      (fun c => completeIpaTranscript pub free.1 c free.2)
  rw [← maskedIpaScalar_simulates pub.point pub.xi pub.value pub.rounds coefficients hxi hv,
    PMF.map_comp]
  rfl

end Distributions

end Zcash.Snark.ZeroKnowledge
