import Zcash.Snark.ZeroKnowledge.Sampling
import Zcash.Snark.ZeroKnowledge.MaskPolynomials
import Zcash.Snark.ZeroKnowledge.MaskSampling
import Zcash.Snark.ZeroKnowledge.IpaSampling
import Zcash.Snark.ZeroKnowledge.IpaAttempt
import Zcash.Snark.ZeroKnowledge.IpaRetry
import Zcash.Snark.ZeroKnowledge.IpaSimulator
import Zcash.Snark.ZeroKnowledge.IpaVerifier
import Zcash.Snark.ZeroKnowledge.LinearMaskTranscript
import Zcash.Snark.ZeroKnowledge.RowMaskTranscript
import Zcash.Snark.ZeroKnowledge.PlonkTranscript
import Zcash.Snark.ZeroKnowledge.PlonkMultiopen
import Zcash.Snark.ZeroKnowledge.PlonkSampling
import Zcash.Snark.ZeroKnowledge.PlonkSimulator
import Zcash.Snark.ZeroKnowledge.PlonkQuotientSimulation
import Zcash.Snark.ZeroKnowledge.PlonkCapacitySimulation
import Zcash.Snark.ZeroKnowledge.PlonkDegreeCertificate
import Zcash.Snark.ZeroKnowledge.PlonkRowSimulation
import Zcash.Snark.ZeroKnowledge.Observation
import Zcash.Meta.AxiomCheck

/-!
# Checked trust boundary of the zero-knowledge development

These pins bound the transitive proof dependencies to Lean's standard axioms. No native-code
axiom or admitted lemma is permitted. Probability distributions are intentionally noncomputable;
the finite sampling program and its declared tape sizes are checked as computable definitions.
`+choice` permits classical choice only in erased proof fields of a plain computable definition;
the checker still rejects noncomputable algorithmic content. No `+native` exemption is used.

The pinned results establish the field-sampling law, both masking constructions, joint
simulation of the IPA stage with supplied or fresh interactive challenges, and joint hiding
of masked columns. The interactive IPA comparison retains errors and emitted prefixes under
supplied codecs; an identity-rejecting codec also gives a checked successful-attempt law and
independent-retry limit. The pre-IPA comparison retains the joint column dependencies, exact
opening groups and emitted scalar order, with supplied challenges and total private constructors.
The computed multi-opening polynomial and folded blind supply a valid IPA input. The joint
pre-IPA/IPA simulation reconstructs that input from the enriched public view, given a public
quotient-evaluation function that agrees with the actual quotient on every reachable row state.
The full batched prover tape is connected to this joint law, and the joint simulator has a
field-coin implementation. The verifier-typed construction computes the constraint numerator
and quotient pieces, and derives quotient agreement using the existing verifier's constraint
function. A public circuit-degree profile now supplies the numerator capacity, with
kernel-checked certificates for the one- and two-Action captured keys. Row-wise constraint
satisfaction supplies exact quotient divisibility. Correctness of the honest lookup and
product row algorithms and the full verifier's grouping still require integration.
These results do not establish a whole-prover simulator, Fiat–Shamir zero-knowledge, or a
Rust-to-Lean refinement.
-/

assert_computable Zcash.Snark.ZeroKnowledge.fieldSampleCount
assert_computable Zcash.Snark.ZeroKnowledge.wordSampleCount
assert_computable Zcash.Snark.ZeroKnowledge.sampleFieldsWith
assert_computable Zcash.Snark.ZeroKnowledge.splitTapeEquiv +choice

assert_axioms Zcash.Snark.ZeroKnowledge.fieldSample
assert_axioms Zcash.Snark.ZeroKnowledge.idealFieldSample
assert_axioms Zcash.Snark.ZeroKnowledge.fieldSample_apply
assert_axioms Zcash.Snark.ZeroKnowledge.fieldSample_weightedBias
assert_axioms Zcash.Snark.ZeroKnowledge.fieldSample_bias_le
assert_axioms Zcash.Snark.ZeroKnowledge.fieldSample_remainder_pos
assert_axioms Zcash.Snark.ZeroKnowledge.fieldSample_zero_gt_light
assert_axioms Zcash.Snark.ZeroKnowledge.fieldSample_ne_ideal
assert_axioms Zcash.Snark.ZeroKnowledge.fieldSample_ne_zero
assert_axioms Zcash.Snark.ZeroKnowledge.wordSampleCount_one
assert_axioms Zcash.Snark.ZeroKnowledge.wordSampleCount_two
assert_axioms Zcash.Snark.ZeroKnowledge.weightedBias_symm
assert_axioms Zcash.Snark.ZeroKnowledge.sampleFieldsWith_queryBound
assert_axioms Zcash.Snark.ZeroKnowledge.sampleFieldsWith_map
assert_axioms Zcash.Snark.ZeroKnowledge.sampleFieldsWith_uniform
assert_axioms Zcash.Snark.ZeroKnowledge.sampleFieldsWith_error_bound
assert_axioms Zcash.Snark.ZeroKnowledge.sampledAttempt_error_bound
assert_axioms Zcash.Snark.ZeroKnowledge.eventBias_map
assert_axioms Zcash.Snark.ZeroKnowledge.eventBias_le_one
assert_axioms Zcash.Snark.ZeroKnowledge.mixedLaws_error_bound

-- Common #225: derive the sparse polynomial and the full scalar from the recursive fold.
assert_computable Zcash.Snark.ZeroKnowledge.coefficientFold +choice
assert_computable Zcash.Snark.ZeroKnowledge.foldByRounds +choice
assert_computable Zcash.Snark.ZeroKnowledge.sparseIpaCoefficients +choice
assert_computable Zcash.Snark.ZeroKnowledge.sparseIpaPolynomial +choice
assert_computable Zcash.Snark.ZeroKnowledge.maskedIpaScalar +choice
assert_axioms Zcash.Snark.ZeroKnowledge.foldByRounds_eq_coefficientFold
assert_axioms Zcash.Snark.ZeroKnowledge.coefficientFold_powerIndex
assert_axioms Zcash.Snark.ZeroKnowledge.coefficientFold_eq_evaluation
assert_axioms Zcash.Snark.ZeroKnowledge.foldByRounds_eq_evaluation
assert_axioms Zcash.Snark.ZeroKnowledge.coeffsToPoly_sparseIpaCoefficients
assert_axioms Zcash.Snark.ZeroKnowledge.sparseIpaPolynomial_eval_root
assert_axioms Zcash.Snark.ZeroKnowledge.coefficientEvaluation_sparseIpaCoefficients
assert_axioms Zcash.Snark.ZeroKnowledge.coefficientFold_sparseIpaCoefficients
assert_axioms Zcash.Snark.ZeroKnowledge.maskedIpaScalar_eq
assert_axioms Zcash.Snark.ZeroKnowledge.maskedIpaScalar_eq_zero_of_evaluation
assert_axioms Zcash.Snark.ZeroKnowledge.affineLinearForm_uniform
assert_axioms Zcash.Snark.ZeroKnowledge.sparseIpaScalar_uniform
assert_axioms Zcash.Snark.ZeroKnowledge.maskedIpaScalar_simulates
assert_axioms Zcash.Snark.ZeroKnowledge.actualSparseIpaScalar_error_bound

-- Common #267: retain the already disclosed evaluation and the unit-weight contribution.
assert_computable Zcash.Snark.ZeroKnowledge.linearMaskPair
assert_computable Zcash.Snark.ZeroKnowledge.linearMaskEquiv +choice
assert_computable Zcash.Snark.ZeroKnowledge.linearMaskView
assert_computable Zcash.Snark.ZeroKnowledge.linearMaskPolynomial +choice
assert_axioms Zcash.Snark.ZeroKnowledge.linearMaskPolynomial_evaluations
assert_axioms Zcash.Snark.ZeroKnowledge.linearMaskPair_uniform
assert_axioms Zcash.Snark.ZeroKnowledge.linearMaskView_uniform
assert_axioms Zcash.Snark.ZeroKnowledge.horner_last_unit_weight
assert_axioms Zcash.Snark.ZeroKnowledge.horner_last_at_zero
assert_axioms Zcash.Snark.ZeroKnowledge.actualLinearMaskView_error_bound

-- Joint Common #267 projection: R, r(x), the Q' commitment, and the later group evaluation.
assert_computable Zcash.Snark.ZeroKnowledge.blindedCommitments
assert_computable Zcash.Snark.ZeroKnowledge.LinearMaskTranscript.ofParts
assert_computable Zcash.Snark.ZeroKnowledge.linearMaskCommitmentCores
assert_computable Zcash.Snark.ZeroKnowledge.honestLinearMaskTranscript
assert_computable Zcash.Snark.ZeroKnowledge.linearMaskTapeEquiv +choice
assert_computable Zcash.Snark.ZeroKnowledge.linearMaskTranscriptFromTape +choice
assert_computable Zcash.Snark.ZeroKnowledge.linearMaskSimulatorFromTape +choice
assert_axioms Zcash.Snark.ZeroKnowledge.blindedCommitments_uniform
assert_axioms Zcash.Snark.ZeroKnowledge.commitmentView_eq
assert_axioms Zcash.Snark.ZeroKnowledge.idealLinearMask_simulation_capstone
assert_axioms Zcash.Snark.ZeroKnowledge.linearMaskTapeEquiv_apply
assert_axioms Zcash.Snark.ZeroKnowledge.uniformTapeLinearMask_eq_idealProver
assert_axioms Zcash.Snark.ZeroKnowledge.linearMaskSimulatorFromTape_uniform
assert_axioms Zcash.Snark.ZeroKnowledge.sampledLinearMask_simulation_error_bound

-- The joint IPA view includes the actual cross terms and the aggregate blind, not just `c`.
assert_computable Zcash.Snark.ZeroKnowledge.publicFold
assert_computable Zcash.Snark.ZeroKnowledge.ipaCrossTerms +choice
assert_computable Zcash.Snark.ZeroKnowledge.ipaCoreMessages +choice
assert_computable Zcash.Snark.ZeroKnowledge.ipaMessageSum +choice
assert_computable Zcash.Snark.ZeroKnowledge.blindIpaMessages
assert_computable Zcash.Snark.ZeroKnowledge.ipaFinalBlind +choice
assert_computable Zcash.Snark.ZeroKnowledge.ipaMaskedVector +choice
assert_computable Zcash.Snark.ZeroKnowledge.honestIpaTranscript +choice
assert_computable Zcash.Snark.ZeroKnowledge.completeIpaTranscript +choice
assert_computable Zcash.Snark.ZeroKnowledge.chooseIpaScalar +choice
assert_computable Zcash.Snark.ZeroKnowledge.ipaSimulatorFromCoins +choice
assert_computable Zcash.Snark.ZeroKnowledge.ipaSampleCount
assert_computable Zcash.Snark.ZeroKnowledge.ipaTapeEquiv +choice
assert_computable Zcash.Snark.ZeroKnowledge.ipaTranscriptFromTape +choice
assert_axioms Zcash.Snark.ZeroKnowledge.ipaCrossTerms_equation
assert_axioms Zcash.Snark.ZeroKnowledge.ipaCoreMessages_equation
assert_axioms Zcash.Snark.ZeroKnowledge.ipaMessageSum_blind
assert_axioms Zcash.Snark.ZeroKnowledge.ipaMaskedVector_eval_zero
assert_axioms Zcash.Snark.ZeroKnowledge.honestIpaTranscript_verifies
assert_axioms Zcash.Snark.ZeroKnowledge.completeIpaTranscript_verifies
assert_axioms Zcash.Snark.ZeroKnowledge.IpaTranscript.eq_complete_of_verifies
assert_axioms Zcash.Snark.ZeroKnowledge.ipaBlindsEquiv_apply
assert_axioms Zcash.Snark.ZeroKnowledge.honestIpaTranscript_fixed_mask
assert_axioms Zcash.Snark.ZeroKnowledge.idealIpa_simulation_capstone
assert_axioms Zcash.Snark.ZeroKnowledge.blinding_bijective_of_card_eq
assert_axioms Zcash.Snark.ZeroKnowledge.chooseIpaScalar_uniform
assert_axioms Zcash.Snark.ZeroKnowledge.idealIpaSimulatorFromFieldCoins_eq
assert_axioms Zcash.Snark.ZeroKnowledge.ipaSampleCount_eq
assert_axioms Zcash.Snark.ZeroKnowledge.ipaSampleCount_eleven
assert_axioms Zcash.Snark.ZeroKnowledge.ipaTapeEquiv_alphas
assert_axioms Zcash.Snark.ZeroKnowledge.ipaTapeEquiv_maskBlind
assert_axioms Zcash.Snark.ZeroKnowledge.ipaTapeEquiv_roundBlinds
assert_axioms Zcash.Snark.ZeroKnowledge.uniformTapeIpa_eq_idealProver
assert_axioms Zcash.Snark.ZeroKnowledge.sampledIpaProver_ideal_error_bound
assert_axioms Zcash.Snark.ZeroKnowledge.sampledIpa_simulation_error_bound

-- Fresh interactive challenges, including zero challenges and partial output on errors.
assert_computable Zcash.Snark.ZeroKnowledge.IpaPublic.withChallenges
assert_computable Zcash.Snark.ZeroKnowledge.ipaNonzeroChallengeIndex
assert_computable Zcash.Snark.ZeroKnowledge.observeIpaRounds +choice
assert_computable Zcash.Snark.ZeroKnowledge.observeIpaAttempt +choice
assert_computable Zcash.Snark.ZeroKnowledge.ipaAttemptObservation +choice
assert_axioms Zcash.Snark.ZeroKnowledge.ipaChallenges_bad_le
assert_axioms Zcash.Snark.ZeroKnowledge.uniformIpaChallenges_bad_le
assert_axioms Zcash.Snark.ZeroKnowledge.wideIpaChallenges_bad_le
assert_axioms Zcash.Snark.ZeroKnowledge.freshIdealIpa_simulation_error_bound
assert_axioms Zcash.Snark.ZeroKnowledge.freshIpa_sampling_error_bound
assert_axioms Zcash.Snark.ZeroKnowledge.freshIpa_simulation_error_bound
assert_axioms Zcash.Snark.ZeroKnowledge.wideFreshIpa_simulation_error_bound
assert_axioms Zcash.Snark.ZeroKnowledge.observeIpaAttempt_mask_failure
assert_axioms Zcash.Snark.ZeroKnowledge.observeIpaRounds_right_failure
assert_axioms Zcash.Snark.ZeroKnowledge.observeIpaRounds_zero_challenge
assert_axioms Zcash.Snark.ZeroKnowledge.observedIpa_simulation_error_bound
assert_axioms Zcash.Snark.ZeroKnowledge.wideObservedIpa_simulation_error_bound

-- Success normalization is derived from the actual observer's failures and retry semantics.
assert_computable Zcash.Snark.ZeroKnowledge.ipaPointFamily
assert_computable Zcash.Snark.ZeroKnowledge.IpaTranscript.pointFamily
assert_computable Zcash.Snark.ZeroKnowledge.ipaPointBlindsIndex
assert_computable Zcash.Snark.ZeroKnowledge.ipaSuccessSet +choice
assert_computable Zcash.Snark.ZeroKnowledge.ipaTranscriptEquiv
assert_axioms Zcash.Snark.ZeroKnowledge.conditioning_mass_ne_zero
assert_axioms Zcash.Snark.ZeroKnowledge.conditioned_event_mass
assert_axioms Zcash.Snark.ZeroKnowledge.conditioned_event_mul_mass
assert_axioms Zcash.Snark.ZeroKnowledge.conditioned_eventBias
assert_axioms Zcash.Snark.ZeroKnowledge.conditioned_simulation_error_bound
assert_axioms Zcash.Snark.ZeroKnowledge.conditioned_common_error_bound
assert_axioms Zcash.Snark.ZeroKnowledge.event_mass_add_compl
assert_axioms Zcash.Snark.ZeroKnowledge.success_mass_lower_bound
assert_axioms Zcash.Snark.ZeroKnowledge.retryStep_event_mass
assert_axioms Zcash.Snark.ZeroKnowledge.conditioned_retry_fixedpoint
assert_axioms Zcash.Snark.ZeroKnowledge.retryStep_error_bound
assert_axioms Zcash.Snark.ZeroKnowledge.boundedRetries_error_bound
assert_axioms Zcash.Snark.ZeroKnowledge.boundedRetries_exhausted
assert_axioms Zcash.Snark.ZeroKnowledge.failure_mass_lt_one
assert_axioms Zcash.Snark.ZeroKnowledge.boundedRetries_tendsto
assert_axioms Zcash.Snark.ZeroKnowledge.exists_success_of_failure_lt_one
assert_axioms Zcash.Snark.ZeroKnowledge.honestIpaPoints_fixed_mask
assert_axioms Zcash.Snark.ZeroKnowledge.idealIpaPoints_uniform
assert_axioms Zcash.Snark.ZeroKnowledge.idealIpaPoint_identity_mass
assert_axioms Zcash.Snark.ZeroKnowledge.idealIpa_identity_le
assert_axioms Zcash.Snark.ZeroKnowledge.observeIpaRounds_complete_iff
assert_axioms Zcash.Snark.ZeroKnowledge.observeIpaAttempt_complete_iff
assert_axioms Zcash.Snark.ZeroKnowledge.ipaSuccess_iff
assert_axioms Zcash.Snark.ZeroKnowledge.uniformIpaRounds_bad_le
assert_axioms Zcash.Snark.ZeroKnowledge.wideIpaRounds_bad_le
assert_axioms Zcash.Snark.ZeroKnowledge.freshIdealIpa_challenges
assert_axioms Zcash.Snark.ZeroKnowledge.freshIdealIpa_identity_le
assert_axioms Zcash.Snark.ZeroKnowledge.freshIdealIpa_failure_le
assert_axioms Zcash.Snark.ZeroKnowledge.wideFreshIpa_failure_le
assert_axioms Zcash.Snark.ZeroKnowledge.ipaRetryFailureBound_eleven_lt_one
assert_axioms Zcash.Snark.ZeroKnowledge.successfulIpa_simulation_error_bound
assert_axioms Zcash.Snark.ZeroKnowledge.wideIpa_retry_failure_le
assert_axioms Zcash.Snark.ZeroKnowledge.wideIpa_eleven_success_support
assert_axioms Zcash.Snark.ZeroKnowledge.IpaPublic.exists_opening
assert_axioms Zcash.Snark.ZeroKnowledge.wideIpaSimulator_success_support
assert_axioms Zcash.Snark.ZeroKnowledge.wideSuccessfulIpa_simulation_capstone
assert_axioms Zcash.Snark.ZeroKnowledge.encodedIpa_retries_tendsto

-- The simulated raw equation is the existing verifier's final IPA assembly.
assert_computable Zcash.Snark.ZeroKnowledge.IpaPublic.ofMsm +choice
assert_computable Zcash.Snark.ZeroKnowledge.IpaTranscript.ofProofString
assert_axioms Zcash.Snark.ZeroKnowledge.publicFold_eq_foldAll
assert_axioms Zcash.Snark.ZeroKnowledge.computeS_gterm_publicFold
assert_axioms Zcash.Snark.ZeroKnowledge.publicFold_evalVector
assert_axioms Zcash.Snark.ZeroKnowledge.ipaMessageSum_eq_roundSum
assert_axioms Zcash.Snark.ZeroKnowledge.ipaTranscript_verifier_capstone
assert_axioms Zcash.Snark.ZeroKnowledge.ipaTranscript_assembleFinalMsm

-- Joint replacement-row rank, with the real domain constant certified without native axioms.
assert_axioms Zcash.Snark.ZeroKnowledge.rootOfUnityFp_primitiveRoot
assert_axioms Zcash.Snark.ZeroKnowledge.omegaOf_primitiveRoot
assert_axioms Zcash.Snark.ZeroKnowledge.omegaOf_rows_injective
assert_computable Zcash.Snark.ZeroKnowledge.maskedRows
assert_computable Zcash.Snark.ZeroKnowledge.maskedRowPolynomial +choice
assert_computable Zcash.Snark.ZeroKnowledge.advicePolynomial +choice
assert_computable Zcash.Snark.ZeroKnowledge.maskRowsLinearMap +choice
assert_computable Zcash.Snark.ZeroKnowledge.rowMaskIndexEquiv +choice
assert_computable Zcash.Snark.ZeroKnowledge.rowMaskTapeEquiv +choice
assert_computable Zcash.Snark.ZeroKnowledge.rowEvaluationsFromTape +choice
assert_computable Zcash.Snark.ZeroKnowledge.maskedColumnCommitmentCore +choice
assert_computable Zcash.Snark.ZeroKnowledge.columnTapeEquiv +choice
assert_computable Zcash.Snark.ZeroKnowledge.maskedColumnFromTape +choice
assert_axioms Zcash.Snark.ZeroKnowledge.surjectiveAddMap_uniform
assert_axioms Zcash.Snark.ZeroKnowledge.surjectiveAffineMap_uniform
assert_axioms Zcash.Snark.ZeroKnowledge.rowMask_interpolationNodes_injective
assert_axioms Zcash.Snark.ZeroKnowledge.rowMask_evaluations_surjective
assert_axioms Zcash.Snark.ZeroKnowledge.rowEvaluationLinearMap_apply
assert_axioms Zcash.Snark.ZeroKnowledge.maskedRows_decompose
assert_axioms Zcash.Snark.ZeroKnowledge.maskedRowPolynomial_joint_uniform
assert_axioms Zcash.Snark.ZeroKnowledge.rowMaskTapeEquiv_apply
assert_axioms Zcash.Snark.ZeroKnowledge.uniformTapeRowEvaluations
assert_axioms Zcash.Snark.ZeroKnowledge.sampledRowEvaluations_error_bound
assert_axioms Zcash.Snark.ZeroKnowledge.advicePolynomial_joint_uniform
assert_axioms Zcash.Snark.ZeroKnowledge.productRowPolynomial_joint_uniform
assert_axioms Zcash.Snark.ZeroKnowledge.columnTapeEquiv_blind
assert_axioms Zcash.Snark.ZeroKnowledge.uniformTapeMaskedColumn
assert_axioms Zcash.Snark.ZeroKnowledge.maskedColumn_joint_uniform
assert_axioms Zcash.Snark.ZeroKnowledge.sampledMaskedColumn_error_bound

-- Successive private columns and the source's batched field tape.
assert_computable Zcash.Snark.ZeroKnowledge.columnRowSampleCount
assert_computable Zcash.Snark.ZeroKnowledge.columnRowsFromCoins +choice
assert_computable Zcash.Snark.ZeroKnowledge.columnRowsFromTape +choice
assert_computable Zcash.Snark.ZeroKnowledge.observeColumnRows +choice
assert_computable Zcash.Snark.ZeroKnowledge.firstTapeEquiv
assert_computable Zcash.Snark.ZeroKnowledge.columnFullSampleCount
assert_computable Zcash.Snark.ZeroKnowledge.columnCoinEquiv +choice
assert_computable Zcash.Snark.ZeroKnowledge.columnMaterialFromTape +choice
assert_computable Zcash.Snark.ZeroKnowledge.batchToColumnTape +choice
assert_computable Zcash.Snark.ZeroKnowledge.batchedColumnSampleCount
assert_computable Zcash.Snark.ZeroKnowledge.batchedToColumnTape +choice
assert_computable Zcash.Snark.ZeroKnowledge.batchedPreIpaTapeEquiv +choice
assert_computable Zcash.Snark.ZeroKnowledge.privateColumnOrder
assert_computable Zcash.Snark.ZeroKnowledge.PrivateColumnId.firstMasked
assert_computable Zcash.Snark.ZeroKnowledge.plonkColumnSteps
assert_computable Zcash.Snark.ZeroKnowledge.privateColumnBatches
assert_computable Zcash.Snark.ZeroKnowledge.plonkColumnBatches
assert_axioms Zcash.Snark.ZeroKnowledge.columnRowSampleCount_eq_sum
assert_axioms Zcash.Snark.ZeroKnowledge.columnRowsFromTape_length
assert_axioms Zcash.Snark.ZeroKnowledge.uniformTapeColumnRows
assert_axioms Zcash.Snark.ZeroKnowledge.idealColumnRows_joint_uniform
assert_axioms Zcash.Snark.ZeroKnowledge.sampledColumnRows_error_bound
assert_axioms Zcash.Snark.ZeroKnowledge.columnFullSampleCount_eq
assert_axioms Zcash.Snark.ZeroKnowledge.columnCoinEquiv_cons_apply
assert_axioms Zcash.Snark.ZeroKnowledge.columnMaterialFromTape_eq
assert_axioms Zcash.Snark.ZeroKnowledge.uniformTapeColumnMaterial
assert_axioms Zcash.Snark.ZeroKnowledge.columnFullSampleCount_append
assert_axioms Zcash.Snark.ZeroKnowledge.batchToColumnTape_fields
assert_axioms Zcash.Snark.ZeroKnowledge.batchedColumnSampleCount_eq
assert_axioms Zcash.Snark.ZeroKnowledge.privateColumnOrder_length
assert_axioms Zcash.Snark.ZeroKnowledge.plonkColumnSteps_length
assert_axioms Zcash.Snark.ZeroKnowledge.plonkColumnSteps_row_samples
assert_axioms Zcash.Snark.ZeroKnowledge.plonkColumns_joint_uniform
assert_axioms Zcash.Snark.ZeroKnowledge.sampledPlonkColumns_error_bound
assert_axioms Zcash.Snark.ZeroKnowledge.privateColumnBatches_flatten
assert_axioms Zcash.Snark.ZeroKnowledge.plonkColumnBatches_flatten
assert_axioms Zcash.Snark.ZeroKnowledge.plonkColumnBatches_sample_count
assert_axioms Zcash.Snark.ZeroKnowledge.plonk_and_ipa_sample_count

-- Joint pre-IPA hiding, retaining all points and correlations among scalar disclosures.
assert_computable Zcash.Snark.ZeroKnowledge.preIpaSampleCount
assert_computable Zcash.Snark.ZeroKnowledge.preIpaCoinEquiv +choice
assert_computable Zcash.Snark.ZeroKnowledge.honestPreIpaMaskView +choice
assert_computable Zcash.Snark.ZeroKnowledge.preIpaMaskViewFromTape +choice
assert_computable Zcash.Snark.ZeroKnowledge.batchedPreIpaViewFromTape +choice
assert_axioms Zcash.Snark.ZeroKnowledge.preIpaMaskViewFromTape_factor
assert_axioms Zcash.Snark.ZeroKnowledge.uniformTapePreIpaMaskView
assert_axioms Zcash.Snark.ZeroKnowledge.preIpaScalarView_uniform
assert_axioms Zcash.Snark.ZeroKnowledge.idealPreIpaMask_simulation_capstone
assert_axioms Zcash.Snark.ZeroKnowledge.sampledPreIpaMask_simulation_error_bound
assert_axioms Zcash.Snark.ZeroKnowledge.uniformTapeBatchedPreIpa
assert_axioms Zcash.Snark.ZeroKnowledge.sampledBatchedPreIpa_simulation_error_bound
assert_axioms Zcash.Snark.ZeroKnowledge.sampledPlonkPreIpa_simulation_error_bound

-- The pinned opening-polynomial groups and actual step-5/step-6 scalar computations.
assert_computable Zcash.Snark.ZeroKnowledge.plonkObservationPoints +choice
assert_computable Zcash.Snark.ZeroKnowledge.privateColumnPolynomial +choice
assert_computable Zcash.Snark.ZeroKnowledge.privateColumnView +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkScalarFold +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkPolynomialFold +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkFixedQueryOrder
assert_computable Zcash.Snark.ZeroKnowledge.plonkAdviceQueryOrder
assert_computable Zcash.Snark.ZeroKnowledge.plonkCollapsedQuotient +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkFirstGroupPrefix +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkPrivateGroupMembers
assert_computable Zcash.Snark.ZeroKnowledge.plonkOpeningGroups +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkOpeningPolynomials +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkFirstGroupOffset +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkPrivateGroupValues +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkEvaluationScalars +choice
assert_computable Zcash.Snark.ZeroKnowledge.PlonkPreIpaTranscript.messages
assert_computable Zcash.Snark.ZeroKnowledge.plonkPreIpaProjection +choice
assert_computable Zcash.Snark.ZeroKnowledge.honestPlonkPreIpaTranscript +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkPreIpaTranscriptFromTape +choice
assert_axioms Zcash.Snark.ZeroKnowledge.privateColumnView_observe
assert_axioms Zcash.Snark.ZeroKnowledge.plonkPolynomialFold_eval
assert_axioms Zcash.Snark.ZeroKnowledge.plonkFirstGroup_eval
assert_axioms Zcash.Snark.ZeroKnowledge.plonkFirstGroup_linearMaskView
assert_axioms Zcash.Snark.ZeroKnowledge.plonkPrivateGroupValues_observe
assert_axioms Zcash.Snark.ZeroKnowledge.honestPlonkPreIpaTranscript_projection
assert_axioms Zcash.Snark.ZeroKnowledge.plonkPreIpaTranscriptFromTape_factor
assert_axioms Zcash.Snark.ZeroKnowledge.sampledPlonkPreIpaTranscript_simulation

-- Computed multi-opening quotients, polynomial commitments, and the actual incoming IPA blind.
assert_computable Zcash.Snark.ZeroKnowledge.polynomialCoefficients +choice
assert_computable Zcash.Snark.ZeroKnowledge.polynomialCommitment +choice
assert_computable Zcash.Snark.ZeroKnowledge.commitmentHornerFold +choice
assert_computable Zcash.Snark.ZeroKnowledge.PolynomialOpeningGroup.values +choice
assert_computable Zcash.Snark.ZeroKnowledge.PolynomialOpeningGroup.interpolant +choice
assert_computable Zcash.Snark.ZeroKnowledge.PolynomialOpeningGroup.vanishing +choice
assert_computable Zcash.Snark.ZeroKnowledge.PolynomialOpeningGroup.quotient +choice
assert_computable Zcash.Snark.ZeroKnowledge.PolynomialOpeningGroup.forVerifier +choice
assert_computable Zcash.Snark.ZeroKnowledge.multiopenQuotientPolynomial +choice
assert_computable Zcash.Snark.ZeroKnowledge.multiopenFinalPolynomial +choice
assert_computable Zcash.Snark.ZeroKnowledge.multiopenFinalBlind +choice
assert_computable Zcash.Snark.ZeroKnowledge.multiopenGroupMsm +choice
assert_computable Zcash.Snark.ZeroKnowledge.computedMultiopenOpening +choice
assert_computable Zcash.Snark.ZeroKnowledge.computedMultiopenIpaPublic +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkOpeningPointSets +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkCollapsedQuotientBlind +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkOpeningPairs +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkBlindedOpeningGroup +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkBlindedOpeningGroups +choice
assert_axioms Zcash.Snark.ZeroKnowledge.coeffsToPoly_polynomialCoefficients
assert_axioms Zcash.Snark.ZeroKnowledge.coefficientEvaluation_polynomialCoefficients
assert_axioms Zcash.Snark.ZeroKnowledge.polynomialCoefficients_horner
assert_axioms Zcash.Snark.ZeroKnowledge.plonkPolynomialFold_natDegree_lt
assert_axioms Zcash.Snark.ZeroKnowledge.polynomialCommitment_zero
assert_axioms Zcash.Snark.ZeroKnowledge.polynomialCommitment_horner
assert_axioms Zcash.Snark.ZeroKnowledge.polynomialCommitment_sum
assert_axioms Zcash.Snark.ZeroKnowledge.polynomialCommitment_fold
assert_axioms Zcash.Snark.ZeroKnowledge.PolynomialOpeningGroup.residual_eval
assert_axioms Zcash.Snark.ZeroKnowledge.PolynomialOpeningGroup.vanishing_monic
assert_axioms Zcash.Snark.ZeroKnowledge.PolynomialOpeningGroup.vanishing_dvd
assert_axioms Zcash.Snark.ZeroKnowledge.PolynomialOpeningGroup.quotient_identity
assert_axioms Zcash.Snark.ZeroKnowledge.opening_denominator_fold
assert_axioms Zcash.Snark.ZeroKnowledge.PolynomialOpeningGroup.quotient_eval
assert_axioms Zcash.Snark.ZeroKnowledge.PolynomialOpeningGroup.quotient_natDegree_lt
assert_axioms Zcash.Snark.ZeroKnowledge.multiopenQuotientPolynomial_eval
assert_axioms Zcash.Snark.ZeroKnowledge.multiopenQuotientPolynomial_natDegree_lt
assert_axioms Zcash.Snark.ZeroKnowledge.computedMultiopenOpening_commitment
assert_axioms Zcash.Snark.ZeroKnowledge.computedMultiopenOpening_value
assert_axioms Zcash.Snark.ZeroKnowledge.multiopenFinalPolynomial_natDegree_lt
assert_axioms Zcash.Snark.ZeroKnowledge.computedMultiopenIpaPublic_validOpening
assert_axioms Zcash.Snark.ZeroKnowledge.plonkOpeningPointSets_nodup
assert_axioms Zcash.Snark.ZeroKnowledge.plonkOpeningPointSets_away
assert_axioms Zcash.Snark.ZeroKnowledge.plonkOpeningPointSets_length
assert_axioms Zcash.Snark.ZeroKnowledge.plonkOpeningPairs_polynomials
assert_axioms Zcash.Snark.ZeroKnowledge.plonkCollapsedQuotient_commitment
assert_axioms Zcash.Snark.ZeroKnowledge.plonkBlindedOpeningGroup_commitment
assert_axioms Zcash.Snark.ZeroKnowledge.privateColumnPolynomial_natDegree_lt
assert_axioms Zcash.Snark.ZeroKnowledge.plonkCollapsedQuotient_natDegree_lt
assert_axioms Zcash.Snark.ZeroKnowledge.linearMaskPolynomial_natDegree_lt
assert_axioms Zcash.Snark.ZeroKnowledge.plonkOpeningGroups_natDegree_lt
assert_axioms Zcash.Snark.ZeroKnowledge.plonkOpeningPolynomials_natDegree_lt
assert_axioms Zcash.Snark.ZeroKnowledge.plonkMultiopenIpa_validOpening
assert_axioms Zcash.Snark.ZeroKnowledge.idealPlonkMultiopenIpa_simulation
assert_axioms Zcash.Snark.ZeroKnowledge.sampledPlonkMultiopenIpa_simulation

-- Actual commitment cores and public reconstruction of the IPA input.
assert_computable Zcash.Snark.ZeroKnowledge.privateColumnIndex
assert_computable Zcash.Snark.ZeroKnowledge.privateColumnAt
assert_computable Zcash.Snark.ZeroKnowledge.plonkOpeningPointIndices
assert_computable Zcash.Snark.ZeroKnowledge.plonkPolynomialOpeningGroups +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkCommitmentPolynomials +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkColumnEntry
assert_computable Zcash.Snark.ZeroKnowledge.plonkLinearEntry
assert_computable Zcash.Snark.ZeroKnowledge.plonkPieceEntry
assert_computable Zcash.Snark.ZeroKnowledge.plonkQuotientPrimeEntry
assert_computable Zcash.Snark.ZeroKnowledge.plonkCommitmentBlindsFromVector
assert_computable Zcash.Snark.ZeroKnowledge.plonkCommitmentCores +choice
assert_computable Zcash.Snark.ZeroKnowledge.honestPlonkMaskView +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkCollapsedQuotientPoint +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkPublicCommitmentMembers +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkPublicGroupCommitments +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkFirstGroupClaims +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkPublicNodeValues +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkPublicOpening +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkPublicIpaInput +choice
assert_axioms Zcash.Snark.ZeroKnowledge.privateColumnOrder_mem
assert_axioms Zcash.Snark.ZeroKnowledge.privateColumnAt_index
assert_axioms Zcash.Snark.ZeroKnowledge.plonkOpeningPointSets_eq_map
assert_axioms Zcash.Snark.ZeroKnowledge.plonkBlindedOpeningGroups_polynomials
assert_axioms Zcash.Snark.ZeroKnowledge.plonkCommitmentPolynomials_column
assert_axioms Zcash.Snark.ZeroKnowledge.plonkCommitmentPolynomials_linear
assert_axioms Zcash.Snark.ZeroKnowledge.plonkCommitmentPolynomials_piece
assert_axioms Zcash.Snark.ZeroKnowledge.plonkCommitmentPolynomials_quotientPrime
assert_axioms Zcash.Snark.ZeroKnowledge.honestPlonkMaskView_points
assert_axioms Zcash.Snark.ZeroKnowledge.honestPlonkMaskView_columns
assert_axioms Zcash.Snark.ZeroKnowledge.honestPlonkMaskView_groupValues
assert_axioms Zcash.Snark.ZeroKnowledge.plonkPublicCommitmentMembers_honest
assert_axioms Zcash.Snark.ZeroKnowledge.plonkPublicGroupCommitments_honest
assert_axioms Zcash.Snark.ZeroKnowledge.plonkPublicNodeValues_honest
assert_axioms Zcash.Snark.ZeroKnowledge.plonkPublicOpening_honest
assert_axioms Zcash.Snark.ZeroKnowledge.plonkPublicIpaInput_honest

-- Joint simulation through the actual private state and complete batched field tape.
assert_computable Zcash.Snark.ZeroKnowledge.plonkMaskViewFromMaterial +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkIpaData +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkPreIpaCoinsEquiv +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkMaterialFromTape +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkJointSampleCount
assert_computable Zcash.Snark.ZeroKnowledge.plonkJointViewFromTape +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkMaskSimulatorFromCoins +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkJointSimulatorFromCoins +choice
assert_axioms Zcash.Snark.ZeroKnowledge.idealPlonkMaterial_rows_mem
assert_axioms Zcash.Snark.ZeroKnowledge.idealPlonkMaterial_maskView
assert_axioms Zcash.Snark.ZeroKnowledge.idealPlonkMaterial_maskView_simulation
assert_axioms Zcash.Snark.ZeroKnowledge.idealPlonkJoint_simulation_capstone
assert_axioms Zcash.Snark.ZeroKnowledge.uniformTapePlonkMaterial
assert_axioms Zcash.Snark.ZeroKnowledge.plonkJointSampleCount_eq
assert_axioms Zcash.Snark.ZeroKnowledge.uniformTapePlonkJoint
assert_axioms Zcash.Snark.ZeroKnowledge.sampledPlonkJoint_simulation_error_bound
assert_axioms Zcash.Snark.ZeroKnowledge.uniformColumnViews_ofFn
assert_axioms Zcash.Snark.ZeroKnowledge.idealPlonkMaskSimulatorFromFieldCoins_eq
assert_axioms Zcash.Snark.ZeroKnowledge.idealPlonkJointSimulatorFromFieldCoins_program
assert_axioms Zcash.Snark.ZeroKnowledge.idealPlonkJointSimulatorFromFieldCoins_eq

-- The actual constraint calculation, computed quotient, and existing proof-string output.
assert_computable Zcash.Snark.ZeroKnowledge.plonkProofShape
assert_computable Zcash.Snark.ZeroKnowledge.plonkProofString
assert_computable Zcash.Snark.ZeroKnowledge.plonkClaimProof
assert_computable Zcash.Snark.ZeroKnowledge.plonkProofFromJointView +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkVerifierHx +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkQueryFactors +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkRotatedColumn +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkPolynomialClaimProof +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkSelectors +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkConstraintModel +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkConstraintNumerator +choice
assert_computable Zcash.Snark.ZeroKnowledge.polynomialCoefficientBlock +choice
assert_computable Zcash.Snark.ZeroKnowledge.domainQuotient +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkQuotient +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkQuotientPieces +choice
assert_computable Zcash.Snark.ZeroKnowledge.plonkHonestQuotientPieces +choice
assert_axioms Zcash.Snark.ZeroKnowledge.plonkProofShape_eleven
assert_axioms Zcash.Snark.ZeroKnowledge.plonkProofString_allExpressions
assert_axioms Zcash.Snark.ZeroKnowledge.plonkVerifierHx_proof
assert_axioms Zcash.Snark.ZeroKnowledge.plonkRotatedColumn_eval
assert_axioms Zcash.Snark.ZeroKnowledge.plonkSelectors_eval
assert_axioms Zcash.Snark.ZeroKnowledge.plonkConstraintNumerator_eq_fold
assert_axioms Zcash.Snark.ZeroKnowledge.plonkConstraintNumerator_eval
assert_axioms Zcash.Snark.ZeroKnowledge.plonkConstraintNumerator_eval_div
assert_axioms Zcash.Snark.ZeroKnowledge.polynomialCoefficientBlock_natDegree_lt
assert_axioms Zcash.Snark.ZeroKnowledge.polynomialCoefficientBlocks_recombine
assert_axioms Zcash.Snark.ZeroKnowledge.polynomialCoefficientBlocks_eval
assert_axioms Zcash.Snark.ZeroKnowledge.domainQuotient_natDegree
assert_axioms Zcash.Snark.ZeroKnowledge.domainQuotient_identity
assert_axioms Zcash.Snark.ZeroKnowledge.plonkQuotientPieces_natDegree_lt
assert_axioms Zcash.Snark.ZeroKnowledge.plonkQuotient_natDegree
assert_axioms Zcash.Snark.ZeroKnowledge.plonkQuotient_natDegree_lt
assert_axioms Zcash.Snark.ZeroKnowledge.plonkQuotient_identity
assert_axioms Zcash.Snark.ZeroKnowledge.plonkQuotientPieces_eval
assert_axioms Zcash.Snark.ZeroKnowledge.plonkHonestQuotient_agrees
assert_axioms Zcash.Snark.ZeroKnowledge.sampledPlonkVerifier_simulation_error_bound

-- Quotient capacity follows from public syntax rather than a private-state degree premise.
assert_axioms Zcash.Snark.ZeroKnowledge.lookupExpressions_natDegree_le
assert_axioms Zcash.Snark.ZeroKnowledge.plonkRotatedColumn_natDegree_le
assert_axioms Zcash.Snark.ZeroKnowledge.canonicalLagrangePolynomials_natDegree_lt
assert_axioms Zcash.Snark.ZeroKnowledge.plonkSelectors_natDegree_le
assert_axioms Zcash.Snark.ZeroKnowledge.constraintModel_natDegree_le
assert_axioms Zcash.Snark.ZeroKnowledge.plonkConstraintNumerator_natDegree_le
assert_axioms Zcash.Snark.ZeroKnowledge.plonkConstraintNumerator_natDegree_lt
assert_axioms Zcash.Snark.ZeroKnowledge.singleAction_plonkDegreeProfile
assert_axioms Zcash.Snark.ZeroKnowledge.multiAction_plonkDegreeProfile
assert_axioms Zcash.Snark.ZeroKnowledge.sampledPlonkVerifier_capacity_simulation_error_bound

-- Row-wise constraint satisfaction supplies exact domain division.
assert_axioms Zcash.Snark.ZeroKnowledge.rowDomain_product
assert_axioms Zcash.Snark.ZeroKnowledge.domainPolynomial_dvd_of_rows
assert_axioms Zcash.Snark.ZeroKnowledge.rows_zero_of_domainPolynomial_dvd
assert_axioms Zcash.Snark.ZeroKnowledge.domainPolynomial_dvd_iff_rows
assert_axioms Zcash.Snark.ZeroKnowledge.plonkPolynomialFold_eval_zero
assert_axioms Zcash.Snark.ZeroKnowledge.plonkConstraintNumerator_dvd_of_rows
assert_axioms Zcash.Snark.ZeroKnowledge.sampledPlonkVerifier_rows_simulation_error_bound

-- At an unmasked row the disclosed evaluation is the original cell, for every mask law.
assert_axioms Zcash.Snark.ZeroKnowledge.maskedRowPolynomial_eval_before
assert_axioms Zcash.Snark.ZeroKnowledge.advicePolynomial_eval_usable
assert_axioms Zcash.Snark.ZeroKnowledge.evaluationView_apply_at_point
assert_axioms Zcash.Snark.ZeroKnowledge.evaluationView_ne_of_disclosed_cell
assert_axioms Zcash.Snark.ZeroKnowledge.adviceEvaluationView_ne_of_usable_cell
assert_axioms Zcash.Snark.ZeroKnowledge.adviceEvaluationView_ne_under_wide_reduction
