-- Generated by scripts/generate_prover_fixtures.py. Do not edit by hand.
namespace Zcash.Snark.Fixtures.Prover

/-- Expected raw hashes and sizes of the authenticated capture inventory. -/
def capturePins : List (String × String × Nat) := [
  ("single-honest.bin.gz", "fb8116ca56831e1c6251c7ee8ca78eb3994ab10bef13d973dc8d5f8f0995c502", 3701648),
  ("multi-honest.bin.gz", "048d723c2733f3fee867f0884d805b2d44c0df0e8f6cac8fd956863aca253f9f", 4376267)
]

end Zcash.Snark.Fixtures.Prover
