#!/usr/bin/env python3
"""Capture complete selected Zakura prover calls, or check their recorded provenance.

The exporter lives in Common under its separate prover fingerprint features.
A pinned source archive supplies the complete producer. Independent verifier
capture drivers must reproduce the existing anchors before a run is usable.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile

from check_zakura_release import (
    MANIFEST, REPO, PinnedArchive, VerificationError, read_manifest, require,
    sha256, verify_sources,
)
from prepare_zakura_release import build_commands, extract_source
from prover_fixture.format import compress, decode, decompress

HERE = Path(__file__).resolve().parent
FIXTURES = REPO / "Zcash/Snark/Fixtures/Prover"
CASE_NAMES = {"single-honest": 1, "multi-honest": 2}
CASE_ANCHORS = {
    "single-honest": ("0x53", "prover_capture", "SingleAction"),
    "multi-honest": ("0x4d", "prover_capture_two_actions", "MultiAction"),
}
PROFILE = "default features, prover-fingerprint, RAYON_NUM_THREADS=1, PostNu6_3, k=11"
PRODUCER = FIXTURES / "producer.json"
IMPLEMENTATION = [HERE / "generate_prover_fixtures.py", HERE / "prover_fixture/format.py"]


def digest(path: Path) -> str:
    return sha256(path.read_bytes())


def source_hashes(root: Path) -> dict[str, str]:
    return {str(path.relative_to(root)): digest(path)
            for path in sorted(root.rglob("*")) if path.is_file()}


def read_producer() -> dict:
    record = json.loads(PRODUCER.read_text())
    require(record["schema_version"] == 1, "unsupported producer pin")
    require(record["repository"] == "https://github.com/zakura-core/common", "noncanonical producer")
    commit = record["commit"]
    require(re.fullmatch(r"[0-9a-f]{40}", commit) is not None, "producer requires a full commit")
    archive = record["archive"]
    require(archive["url"] == f"https://codeload.github.com/zakura-core/common/tar.gz/{commit}" and
            archive["prefix"] == f"common-{commit}" and archive["file"] == "common-prover-source.tar.gz",
            "producer archive must use its canonical commit")
    require(re.fullmatch(r"[0-9a-f]{64}", archive["sha256"]) is not None, "invalid producer archive hash")
    require(record["release_commit"] == read_manifest()["common"]["commit"], "producer release changed")
    require(isinstance(record["release_delta"], dict) and record["release_delta"], "missing release delta")
    for path, change in record["release_delta"].items():
        require(not Path(path).is_absolute() and ".." not in Path(path).parts, "invalid source path")
        require(set(change) == {"release_sha256", "producer_sha256"}, "invalid source delta")
        require(change["release_sha256"] != change["producer_sha256"], "unchanged source delta")
        for value in change.values():
            require(value is None or re.fullmatch(r"[0-9a-f]{64}", value) is not None,
                    "invalid source checksum")
    return record


def capture_commands(release: dict, target: str, source: Path) -> list[dict]:
    prefix = ["cargo", "+" + release["common"]["toolchain"]]
    package = ["--locked", "--target", target, "-p", "zakura-orchard", "--features", "prover-fingerprint"]
    commands = [{"kind": "features", "label": "prover/features", "argv": prefix + ["tree"] + package + ["-e", "features"],
                 "environment": {"RAYON_NUM_THREADS": "1"}, "outputs": [], "output_variables": []}]
    rust = (source / "crates/orchard/src/circuit/prover_fingerprint.rs").read_text()
    for name, suffix, variable in [("single-honest", "", "SINGLE"), ("multi-honest", "_two_actions", "MULTI")]:
        driver = "circuit::prover_fingerprint::prover_capture" + suffix
        require(re.search(rf"\bfn prover_capture{suffix}\s*\(", rust) is not None, "missing producer driver")
        output = name + ".bin"
        key = f"ORCHARD_LEAN_{variable}_PROVER_OUT"
        commands.append({"kind": "test", "capture_kind": "prover", "case": name, "label": "prover/" + name,
                         "argv": prefix + ["test"] + package + ["--release", "--lib", driver,
                                                                  "--", "--exact", "--nocapture", "--test-threads=1"],
                         "environment": {"RAYON_NUM_THREADS": "1", key: output},
                         "outputs": [{"path": output}], "output_variables": [key]})
    for command in build_commands(release, target, source):
        name = command["label"].split("/")[-1]
        if command["kind"] == "test" and name in CASE_NAMES:
            commands.append(command | {"capture_kind": "verifier", "case": name})
    require(len(commands) == 5, "expected feature report and four exact capture drivers")
    return commands


def pins(record: dict) -> str:
    lines = ["-- Generated by scripts/generate_prover_fixtures.py. Do not edit by hand.",
             "namespace Zcash.Snark.Fixtures.Prover", "",
             "/-- Expected raw hashes and sizes of the authenticated capture inventory. -/",
             "def capturePins : List (String × String × Nat) := ["]
    cases = record["cases"]
    for i, case in enumerate(cases):
        comma = "," if i + 1 < len(cases) else ""
        lines.append(f'  ("{case["file"]}", "{case["raw_sha256"]}", {case["raw_bytes"]}){comma}')
    lines += ["]", "", "end Zcash.Snark.Fixtures.Prover", ""]
    return "\n".join(lines)


def check_local() -> None:
    release = read_manifest()
    producer = read_producer()
    record = json.loads((FIXTURES / "manifest.json").read_text())
    require(record["schema_version"] == 1, "unsupported prover manifest")
    require(record["release_manifest_sha256"] == digest(MANIFEST), "release manifest changed")
    require(record["common_commit"] == release["common"]["commit"], "Common revision changed")
    require(record["toolchain"] == release["common"]["toolchain"] and record["profile"] == PROFILE,
            "capture build profile changed")
    require(record["producer_sha256"] == digest(PRODUCER) and record["producer_commit"] == producer["commit"],
            "producer pin changed; regenerate the fixtures")
    require(record["generator"] == {str(p.relative_to(REPO)): digest(p) for p in IMPLEMENTATION},
            "capture implementation changed; regenerate the fixtures")
    require([case["name"] for case in record["cases"]] == list(CASE_NAMES), "unexpected prover case set")
    expected_files = {name + ".bin.gz" for name in CASE_NAMES}
    require({p.name for p in FIXTURES.glob("*.bin*")} == expected_files, "unrecorded or missing prover capture")
    for case in record["cases"]:
        name = case["name"]
        require(case["file"] == name + ".bin.gz", "unexpected capture path")
        seed, driver, family = CASE_ANCHORS[name]
        require(case["actions"] == CASE_NAMES[name] and case["seed_byte"] == seed and
                case["driver"] == "circuit::prover_fingerprint::" + driver and
                case["verifier_fixture"] == f"Zcash/Snark/Fixtures/{family}/Honest/Fixture.lean",
                f"capture driver or verifier anchor changed: {name}")
        stored = (FIXTURES / case["file"]).read_bytes()
        require(sha256(stored) == case["gzip_sha256"], f"stored capture changed: {name}")
        raw = decompress(stored)
        require((len(raw), sha256(raw)) == (case["raw_bytes"], case["raw_sha256"]),
                f"raw capture changed: {name}")
        decoded = decode(raw, CASE_NAMES[name])
        require({str(k): v for k, v in decoded["counts"].items()} == case["event_counts"],
                f"event counts changed: {name}")
        require(digest(REPO / case["verifier_fixture"]) == case["verifier_sha256"],
                f"existing verifier anchor changed: {name}")
    require((FIXTURES / "Pins.lean").read_text() == pins(record), "Lean capture pins are stale")
    print("prover fixtures: both complete captures, implementation hashes and verifier anchors match")


def prepare(root: Path, cache: Path, fetch: bool, target: str) -> dict:
    release = read_manifest()
    verify_sources(release, cache, fetch=fetch)
    producer = read_producer()
    archive = PinnedArchive(release["common"]["archive"], cache)
    try:
        original, _ = extract_source(archive, root / "release-common")
    finally:
        archive.close()
    archive = PinnedArchive(producer["archive"], cache, fetch=fetch)
    try:
        after, links = extract_source(archive, root / "common")
    finally:
        archive.close()
    changes = {path: {"release_sha256": original.get(path), "producer_sha256": after.get(path)}
               for path in sorted(set(original) | set(after)) if original.get(path) != after.get(path)}
    require(changes == producer["release_delta"], "producer/release source differences changed")
    require(after["Cargo.lock"] == original["Cargo.lock"] and
            after["rust-toolchain.toml"] == original["rust-toolchain.toml"], "producer changed release dependencies")
    plan = {"schema_version": 1, "release_manifest_sha256": digest(MANIFEST),
            "producer_sha256": digest(PRODUCER), "producer_commit": producer["commit"],
            "target": target, "toolchain": release["common"]["toolchain"],
            "source_files": after, "materialized_source_links": links,
            "generator": {str(p.relative_to(REPO)): digest(p) for p in IMPLEMENTATION},
            "commands": capture_commands(release, target, root / "common")}
    (root / "plan.json").write_text(json.dumps(plan, indent=2) + "\n")
    return plan


def check_prepared(root: Path, plan: dict) -> None:
    require(digest(MANIFEST) == plan["release_manifest_sha256"], "prepared release manifest changed")
    require(plan["producer_sha256"] == digest(PRODUCER), "prepared producer pin changed")
    require(plan["generator"] == {str(p.relative_to(REPO)): digest(p) for p in IMPLEMENTATION},
            "prepared generator changed")
    require(source_hashes(root / "common") == plan["source_files"], "prepared source tree changed")


def execute(root: Path, plan: dict, target_dir: Path | None) -> dict:
    check_prepared(root, plan)
    env = os.environ.copy()
    for key in ("RUSTFLAGS", "CARGO_ENCODED_RUSTFLAGS", "RUSTC_WRAPPER", "RUSTC_WORKSPACE_WRAPPER"):
        env.pop(key, None)
    env.update(CARGO_TARGET_DIR=str(target_dir or root / "target"), CARGO_TERM_COLOR="never")
    result = {"status": "running", "plan_sha256": digest(root / "plan.json"), "commands": []}

    def save() -> None:
        (root / "results.json").write_text(json.dumps(result, indent=2) + "\n")

    save()
    try:
        version = subprocess.run(["rustc", "+" + plan["toolchain"], "-vV"], env=env,
                                 check=True, capture_output=True, text=True).stdout
        require("host: " + plan["target"] + "\n" in version, "capture requires its named native target")
        (root / "rustc.txt").write_text(version)
        for index, command in enumerate(plan["commands"]):
            name = command.get("case")
            run_env = env | command["environment"]
            for key in command["output_variables"]:
                path = root / run_env[key]
                require(not path.exists(), "refusing to reuse a capture")
                path.parent.mkdir(parents=True, exist_ok=True)
                run_env[key] = str(path)
            print(f"[{index + 1}/{len(plan['commands'])}] {command['label']}", flush=True)
            log = root / f"command-{index:03d}.log"
            with log.open("w") as output:
                completed = subprocess.run(command["argv"], cwd=root / "common", env=run_env,
                                           stdout=output, stderr=subprocess.STDOUT)
            result["commands"].append({"label": command["label"], "returncode": completed.returncode,
                                       "log": log.name, "log_sha256": digest(log)})
            save()
            require(completed.returncode == 0, f"capture command failed: {log}")
            if command["kind"] == "test":
                summaries = re.findall(r"test result: ok\. (\d+) passed; (\d+) failed; (\d+) ignored;",
                                       log.read_text(errors="replace"))
                require(summaries == [("1", "0", "0")], "expected exactly one passing capture test")
                if command["capture_kind"] == "prover":
                    decode((root / (name + ".bin")).read_bytes(), CASE_NAMES[name])
                else:
                    for output in command["outputs"]:
                        require((root / output["path"]).read_bytes() == (REPO / output["destination"]).read_bytes(),
                                f"producer changed existing verifier capture: {name}")
        check_prepared(root, plan)
        result["status"] = "passed"
    except BaseException as error:
        result["status"] = "failed"
        result["error"] = str(error)
        raise
    finally:
        save()
    return result


def install_or_compare(root: Path, plan: dict, update: bool) -> None:
    check_prepared(root, plan)
    result = json.loads((root / "results.json").read_text())
    require(result["status"] == "passed" and result["plan_sha256"] == digest(root / "plan.json"),
            "capture run did not complete successfully")
    require(len(result["commands"]) == len(plan["commands"]), "incomplete capture commands")
    for command, execution in zip(plan["commands"], result["commands"]):
        require(execution["label"] == command["label"] and execution["returncode"] == 0 and
                digest(root / execution["log"]) == execution["log_sha256"], "capture command evidence changed")
    release = read_manifest()
    record = {"schema_version": 1, "release_manifest_sha256": digest(MANIFEST),
              "common_commit": release["common"]["commit"], "toolchain": plan["toolchain"],
              "profile": PROFILE,
              "producer_sha256": plan["producer_sha256"], "producer_commit": plan["producer_commit"],
              "generator": plan["generator"], "cases": []}
    artifacts = {}
    for command in plan["commands"]:
        if command.get("capture_kind") != "prover":
            continue
        name = command["case"]
        raw = (root / (name + ".bin")).read_bytes()
        decoded = decode(raw, CASE_NAMES[name])
        verifier, = [item for item in plan["commands"]
                     if item.get("capture_kind") == "verifier" and item["case"] == name]
        output, = verifier["outputs"]
        require((root / output["path"]).read_bytes() == (REPO / output["destination"]).read_bytes(),
                f"producer changed verifier capture: {name}")
        stored = compress(raw)
        case = {"name": name, "file": name + ".bin.gz", "actions": CASE_NAMES[name],
                "seed_byte": output["seed_byte"], "driver": command["argv"][command["argv"].index("--") - 1],
                "raw_sha256": sha256(raw), "raw_bytes": len(raw), "gzip_sha256": sha256(stored),
                "event_counts": {str(k): v for k, v in decoded["counts"].items()},
                "verifier_fixture": output["destination"],
                "verifier_sha256": digest(REPO / output["destination"])}
        record["cases"].append(case)
        artifacts[case["file"]] = stored
        if not update:
            require(decompress((FIXTURES / case["file"]).read_bytes()) == raw,
                    f"regenerated prover execution differs: {name}")
    if update:
        FIXTURES.mkdir(parents=True, exist_ok=True)
        for name, stored in artifacts.items():
            (FIXTURES / name).write_bytes(stored)
        (FIXTURES / "manifest.json").write_text(json.dumps(record, indent=2) + "\n")
        (FIXTURES / "Pins.lean").write_text(pins(record))
    check_local()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="check local captures without compiling")
    parser.add_argument("--extract", type=Path, help="with --check, unpack authenticated captures for Lean")
    parser.add_argument("--update", action="store_true", help="install successful captures and provenance")
    parser.add_argument("--from-run", type=Path, help="reuse a completed, authenticated capture run")
    parser.add_argument("--cache-dir", type=Path, default=Path(os.environ.get("ZAKURA_SOURCE_CACHE", "scripts/generated/zakura-cache")))
    parser.add_argument("--work-dir", type=Path, default=Path(os.environ.get("REGEN_WORK_DIR", "scripts/generated/prover")))
    parser.add_argument("--target-dir", type=Path, help="reuse Cargo artifacts, never capture outputs")
    parser.add_argument("--fetch", action="store_true", help="download missing authenticated release archives")
    args = parser.parse_args()
    if args.check:
        require(not args.update and args.from_run is None, "--check cannot install or execute a run")
        check_local()
        if args.extract:
            args.extract.mkdir(parents=True, exist_ok=True)
            for name in CASE_NAMES:
                (args.extract / (name + ".bin")).write_bytes(
                    decompress((FIXTURES / (name + ".bin.gz")).read_bytes()))
        return
    require(args.extract is None, "--extract requires --check")
    if args.from_run:
        root = args.from_run.resolve()
        plan = json.loads((root / "plan.json").read_text())
        # A reused evidence directory cannot supply its own source or command authority.
        with tempfile.TemporaryDirectory(prefix="prover-auth-") as audit:
            expected = prepare(Path(audit), args.cache_dir.resolve(), args.fetch, plan["target"])
            require(plan == expected, "reused plan differs from the authenticated producer and commands")
    else:
        toolchain = read_manifest()["common"]["toolchain"]
        version = subprocess.run(["rustc", "+" + toolchain, "-vV"], check=True,
                                 capture_output=True, text=True).stdout
        target = next(line.removeprefix("host: ") for line in version.splitlines() if line.startswith("host: "))
        args.work_dir.mkdir(parents=True, exist_ok=True)
        root = Path(tempfile.mkdtemp(prefix="capture-", dir=args.work_dir.resolve()))
        print(f"Capture evidence: {root}", flush=True)
        plan = prepare(root, args.cache_dir.resolve(), args.fetch, target)
        execute(root, plan, args.target_dir.resolve() if args.target_dir else None)
    install_or_compare(root, plan, args.update)


if __name__ == "__main__":
    try:
        main()
    except (VerificationError, ValueError, OSError, subprocess.SubprocessError) as error:
        print(f"prover fixture check failed: {error}", file=sys.stderr)
        raise SystemExit(1)
