#!/usr/bin/env python3
"""Copy Rust-exported verifier or prover fixtures, or check a completed run.

--check-set performs only local inventory checks. Other modes use Rust unless
--from-run names an already completed fixture run. --update installs its exact
outputs and refreshes their provenance; it does not run Lean or assert ZK of Rust.
"""

from __future__ import annotations

import argparse
import copy
import json
import os
from pathlib import Path
import platform
import re
import shlex
import subprocess
import sys
import tempfile

from check_zakura_release import (
    MANIFEST, REPO, PinnedArchive, VerificationError, compare_public_artifacts,
    read_manifest, relative_path, require, sha256, verify_sources,
)
from prepare_zakura_release import (
    FIXTURE_DESTINATIONS, PROVER_DESTINATIONS, PROVER_PIN, build_commands,
    extract_fixture_source, fixture_source,
)


EXPORTER_HEADER = re.compile(
    r"-- Auto-generated by halo2 `dump_vesta_lean_(prover_fixture|fixture(_match_only)?)`\. Do not edit by hand\.")


def expected_paths(suite: str | None = None) -> set[str]:
    paths = {directory + "/Fixture.lean" for directory in FIXTURE_DESTINATIONS.values()}
    paths.update(directory + "/proof-bytes.hex" for name, directory in FIXTURE_DESTINATIONS.items()
                 if name.endswith("-random"))
    if suite == "fixtures":
        return paths
    if suite == "prover-fixtures":
        return set(PROVER_DESTINATIONS.values())
    return paths | set(PROVER_DESTINATIONS.values())


def check_artifact_set(repo: Path) -> None:
    root = repo / "Zcash/Snark/Fixtures"
    found = set()
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        generated = False
        if path.suffix == ".lean":
            with path.open() as source:
                generated = EXPORTER_HEADER.fullmatch(source.readline().rstrip("\n")) is not None
        if path.name == "Fixture.lean":
            require(generated, f"fixture lacks the exporter header: {path.relative_to(repo)}")
        if generated or path.name == "Fixture.lean" or path.suffix == ".hex":
            require(not path.is_symlink() and path.resolve().is_relative_to(repo.resolve()),
                    "fixture artifact must be a regular file inside the repository")
            found.add(str(path.relative_to(repo)))
    require(found == expected_paths(), "capture-artifact set differs from the pinned artifacts")


def completed_captures(run: Path, manifest: dict) -> tuple[dict, dict[str, bytes]]:
    """Check a recorded successful run before comparing or installing any artifact."""
    require((run / "results.json").is_file(), "capture run has no results.json; execute its run.py first")
    plan_bytes = (run / "plan.json").read_bytes()
    plan = json.loads(plan_bytes)
    results = json.loads((run / "results.json").read_text())
    require(results["status"] == "passed", "capture run did not pass")
    require(results["plan_sha256"] == sha256(plan_bytes), "executed plan hash differs")
    suite = plan["suite"]
    require(suite in {"fixtures", "prover-fixtures"}, "expected a fixture suite")
    if suite == "prover-fixtures":
        require(plan["producer_sha256"] == sha256(PROVER_PIN.read_bytes()), "prover exporter pin changed")
    snapshot_bytes = (run / "release.json").read_bytes()
    require(sha256(snapshot_bytes) == plan["manifest_sha256"], "prepared release record changed")
    snapshot = json.loads(snapshot_bytes)
    # Installing captures changes their provenance, not the release/protocol pins.
    stable = lambda data: {key: value for key, value in data.items()
                           if key not in {"existing_capture", "validation_boundary"}}
    require(stable(snapshot) == stable(manifest), "capture run targets different release pins")
    require(plan["commands"] == build_commands(manifest, plan["target"], run / "common", suite=suite),
            "capture commands differ from the pinned Rust drivers")
    require(len(results["commands"]) == len(plan["commands"]), "incomplete capture command results")
    for index, (command, result) in enumerate(zip(plan["commands"], results["commands"])):
        require(all(result[key] == command[key] for key in ("label", "argv", "environment"))
                and result["returncode"] == 0, "capture command result differs")
        require(result["log"] == f"command-{index:03d}.log", "unexpected capture log path")
        log = (run / result["log"]).read_bytes()
        require(sha256(log) == result["log_sha256"], "capture log changed")
        if command["kind"] == "test":
            summaries = re.findall(r"test result: ok\. (\d+) passed; (\d+) failed; (\d+) ignored;",
                                   log.decode(errors="replace"))
            require(summaries == [("1", "0", "0")], "capture driver did not execute exactly once")
    outputs = [output for command in plan["commands"] for output in command["outputs"]]
    require(len(outputs) == len(expected_paths(suite))
            and {output["destination"] for output in outputs} == expected_paths(suite),
            "capture destinations differ from the pinned suite")
    require(len(results["captures"]) == len(outputs), "incomplete capture results")
    captures = {}
    for output, result in zip(outputs, results["captures"]):
        path = run / relative_path(output["path"])
        require(path.resolve().is_relative_to(run.resolve()) and not path.is_symlink(),
                "capture path leaves the prepared directory")
        data = path.read_bytes()
        require(data and result == output | {"sha256": sha256(data)}, "capture bytes or metadata changed")
        destination = output["destination"]
        if destination.endswith(".lean"):
            generator = ("dump_vesta_lean_prover_fixture" if suite == "prover-fixtures" else
                         "dump_vesta_lean_fixture_match_only" if "/Random/" in destination else
                         "dump_vesta_lean_fixture")
            header = f"-- Auto-generated by halo2 `{generator}`. Do not edit by hand."
            require(data.splitlines()[0] == header.encode(), "capture has the wrong exporter mode")
        captures[destination] = data
    return plan, captures


def check_run_sources(run: Path, plan: dict, manifest: dict, cache: Path) -> None:
    """Bind the prepared source inventory to the authenticated Common archive."""
    with tempfile.TemporaryDirectory(prefix="zakura-source-check-") as temporary:
        hashes, links = extract_fixture_source(manifest, plan.get("suite", "fixtures"), cache,
                                              Path(temporary) / "common")
    require(plan["source_files"] == hashes and plan["materialized_source_links"] == links,
            "capture source inventory differs from the pinned archive")
    actual = {str(path.relative_to(run / "common")) for path in (run / "common").rglob("*")
              if path.is_file() or path.is_symlink()}
    require(actual == set(hashes), "prepared source tree has missing or extra files")
    for relative, expected in hashes.items():
        path = run / "common" / relative_path(relative)
        require(path.resolve().is_relative_to((run / "common").resolve())
                and not path.is_symlink() and sha256(path.read_bytes()) == expected,
                f"capture source changed: {relative}")


def install_captures(repo: Path, manifest: dict, plan: dict, captures: dict[str, bytes]) -> None:
    """Install whole generated files and their pins after all run/source checks succeed."""
    suite = plan["suite"]
    require(set(captures) == expected_paths(suite), "refusing an incomplete fixture installation")
    updated = copy.deepcopy(manifest)
    if suite == "fixtures":
        updated["existing_capture"]["sha256"] = sha256(captures[updated["existing_capture"]["path"]])
    updated["existing_capture"]["limitations"] = [
        "The verifier capture was regenerated from the pinned Zakura Common release.",
        "Verifier captures check the sampled executions, not the prover's randomness distribution.",
        "The separate circuit/layout dumps retain their original provenance.",
    ]
    updated["validation_boundary"] = (
        "Verifier fixtures were regenerated from pinned Zakura Rust and their provenance updated. "
        "Lean elaboration remains required. Rust-to-Lean correspondence is an implementation assumption.")
    version = next(package["version"] for package in manifest["packages"]
                   if package["name"] == "zakura-halo2-proofs")
    rows = ["# Per-artifact provenance for the machine-generated fingerprint captures.",
            "# Tab-separated: path, sha256, generator, source, invocation.",
            "# Regenerate with scripts/regenerate-{fingerprint,prover}-fixtures.sh; validate with check_fixture_manifest.sh."]
    provenance = repo / "Zcash/Snark/Fixtures/MANIFEST.tsv"
    if provenance.exists():
        rows += [line for line in provenance.read_text().splitlines()
                 if line and not line.startswith("#") and line.split("\t")[0] not in captures]
    for command in plan["commands"]:
        for output in command["outputs"]:
            destination = output["destination"]
            generator = ("dump_vesta_lean_prover_fixture" if suite == "prover-fixtures" else
                         "match-only proof bytes" if destination.endswith(".hex") else
                         "dump_vesta_lean_fixture_match_only" if "/Random/" in destination else
                         "dump_vesta_lean_fixture")
            invocation = shlex.join(command["argv"]) + "; " + ", ".join(command["output_variables"])
            rows.append("\t".join([destination, sha256(captures[destination]),
                                   f"{generator} (zakura-halo2-proofs {version})",
                                   f"zakura-core/common@{fixture_source(manifest, suite)['commit']}", invocation]))
    writes = captures | {
        "Zcash/Snark/Fixtures/MANIFEST.tsv": ("\n".join(rows) + "\n").encode(),
    }
    if suite == "fixtures":
        writes[str(MANIFEST.relative_to(REPO))] = (json.dumps(updated, indent=2) + "\n").encode()
    for relative in writes:
        path = repo / relative_path(relative)
        require(path.resolve().is_relative_to(repo.resolve()) and not path.is_symlink(),
                "fixture installation destination leaves the repository")
    for relative, data in writes.items():
        (repo / relative_path(relative)).write_bytes(data)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check-set", action="store_true")
    parser.add_argument("--prover", action="store_true", help="regenerate the separate prover Lean fixtures")
    parser.add_argument("--from-run", type=Path, help="check an already completed fixture run; do not run Rust")
    parser.add_argument("--cache-dir", type=Path, help="authenticated source archive cache")
    parser.add_argument("--update", action="store_true", help="install the selected Rust outputs and provenance")
    args = parser.parse_args()
    if args.check_set and (args.from_run or args.update or args.cache_dir):
        parser.error("--check-set cannot be combined with regeneration options")
    try:
        check_artifact_set(REPO)
        if args.check_set:
            print("capture-artifact set matches the pinned verifier and prover artifacts, with exporter headers.")
            return
        manifest = read_manifest()
        suite = "prover-fixtures" if args.prover else "fixtures"
        work = Path(os.environ.get("REGEN_WORK_DIR", str(REPO / "scripts/generated/zakura"))).resolve()
        cache = args.cache_dir or Path(os.environ.get("ZAKURA_SOURCE_CACHE", str(work / "sources")))
        run = args.from_run.resolve() if args.from_run else None
        if run is not None:
            plan, captures = completed_captures(run, manifest)
            require(plan["suite"] == suite, "completed run targets a different fixture suite")
        verify_sources(manifest, cache, fetch=True)
        if args.prover:
            PinnedArchive(fixture_source(manifest, suite)["archive"], cache, fetch=True).close()
        if run is None:
            targets = {("Darwin", "arm64"): "aarch64-apple-darwin",
                       ("Linux", "x86_64"): "x86_64-unknown-linux-gnu",
                       ("Linux", "aarch64"): "aarch64-unknown-linux-gnu"}
            target = targets.get((platform.system(), platform.machine()))
            require(target is not None, "unsupported native fixture target")
            work.mkdir(parents=True, exist_ok=True)
            parent = Path(tempfile.mkdtemp(prefix="run-", dir=work))
            run = parent / "fixtures"
            subprocess.run([sys.executable, str(REPO / "scripts/prepare_zakura_release.py"),
                            "--cache-dir", str(cache), "--output-dir", str(run),
                            "--suite", suite, "--target", target], check=True)
            print(f"Fixture run and logs: {run}", flush=True)
            subprocess.run(["rustup", "show"], cwd=run / "common", check=True)
            subprocess.run([sys.executable, str(run / "run.py")], check=True)
            plan, captures = completed_captures(run, manifest)
        check_run_sources(run, plan, manifest, cache)
        if not args.prover:
            archive = PinnedArchive(manifest["common"]["archive"], cache)
            try:
                with tempfile.TemporaryDirectory(prefix="zakura-capture-check-") as temporary:
                    staged = Path(temporary)
                    capture = staged / manifest["existing_capture"]["path"]
                    capture.parent.mkdir(parents=True)
                    capture.write_bytes(captures[manifest["existing_capture"]["path"]])
                    compare_public_artifacts(archive, manifest, staged)
            finally:
                archive.close()
        if args.update:
            install_captures(REPO, manifest, plan, captures)
            print(f"Installed {len(captures)} Rust-generated artifacts and their provenance; Lean checks remain required.")
        else:
            mismatches = [relative for relative, data in captures.items() if (REPO / relative).read_bytes() != data]
            require(not mismatches, "committed fixtures differ from Zakura captures: " + ", ".join(mismatches)
                    + f"; completed run: {run}")
            print(f"All {len(captures)} selected artifacts match the pinned Rust exports byte-for-byte.")
    except (VerificationError, OSError, KeyError, ValueError, subprocess.CalledProcessError) as error:
        parser.exit(1, f"fixture regeneration failed: {error}\n")


if __name__ == "__main__":
    main()
