"""Mutation checks for fixture inventory, completed-run records and provenance updates.

All captures and logs here are synthetic tooling fixtures. No Rust or Lean is run.
"""

import copy
import io
import json
from pathlib import Path
import tarfile
import tempfile
import unittest

from check_zakura_release import MANIFEST, REPO, VerificationError, read_manifest, sha256
from prepare_zakura_release import build_commands
from regenerate_fingerprint_fixtures import (
    check_artifact_set, check_run_sources, completed_captures, expected_paths, install_captures,
)


class FixtureRegenerationTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name)
        self.repo = self.root / "repo"
        self.run = self.root / "run"
        self.manifest = read_manifest()
        rust = self.run / "common/crates/orchard/src/circuit/fingerprint/mod.rs"
        rust.parent.mkdir(parents=True)
        rust.write_text("""
fn fingerprint_capture() {}
fn fingerprint_capture_two_actions() {}
fn fingerprint_capture_random() {}
fn fingerprint_capture_random_two_actions() {}
fn fingerprint_capture_random_three_actions() {}
""")
        snapshot = (json.dumps(self.manifest) + "\n").encode()
        (self.run / "release.json").write_bytes(snapshot)
        self.plan = {"suite": "fixtures", "target": "aarch64-apple-darwin",
                     "manifest_sha256": sha256(snapshot),
                     "commands": build_commands(self.manifest, "aarch64-apple-darwin", self.run / "common")}
        self.results = {"status": "passed", "commands": [], "captures": []}
        for index, command in enumerate(self.plan["commands"]):
            log = b"features\n" if command["kind"] == "features" else b"test result: ok. 1 passed; 0 failed; 0 ignored;\n"
            name = f"command-{index:03d}.log"
            (self.run / name).write_bytes(log)
            self.results["commands"].append({key: command[key] for key in ("label", "argv", "environment")} |
                                            {"returncode": 0, "log": name, "log_sha256": sha256(log)})
            for output in command["outputs"]:
                destination = output["destination"]
                mode = "_match_only" if "/Random/" in destination else ""
                data = (f"-- Auto-generated by halo2 `dump_vesta_lean_fixture{mode}`. Do not edit by hand.\n"
                        f"-- synthetic tooling fixture: {destination}\n").encode()
                if destination.endswith(".hex"):
                    data = b"cafe\n"
                generated = self.run / output["path"]
                generated.parent.mkdir(parents=True, exist_ok=True)
                generated.write_bytes(data)
                committed = self.repo / destination
                committed.parent.mkdir(parents=True, exist_ok=True)
                committed.write_bytes(data + b"old\n")
                self.results["captures"].append(output | {"sha256": sha256(data)})
        self.save()

    def save(self):
        plan = (json.dumps(self.plan) + "\n").encode()
        (self.run / "plan.json").write_bytes(plan)
        self.results["plan_sha256"] = sha256(plan)
        (self.run / "results.json").write_text(json.dumps(self.results))

    def test_inventory_rejects_missing_extra_renamed_and_symlinked_artifacts(self):
        check_artifact_set(self.repo)
        relative = sorted(expected_paths())[0]
        path = self.repo / relative
        original = path.read_bytes()
        path.unlink()
        with self.assertRaises(VerificationError):
            check_artifact_set(self.repo)
        path.write_bytes(original)
        extra = path.parent / "unexpected.hex"
        extra.write_text("00")
        with self.assertRaises(VerificationError):
            check_artifact_set(self.repo)
        extra.unlink()
        extra = path.parent / "HiddenCapture.lean"
        extra.write_bytes(original)
        with self.assertRaises(VerificationError):
            check_artifact_set(self.repo)
        extra.unlink()
        path.unlink()
        elsewhere = self.root / "outside.lean"
        elsewhere.write_bytes(original)
        path.symlink_to(elsewhere)
        with self.assertRaises(VerificationError):
            check_artifact_set(self.repo)

    def test_completed_run_rejects_failure_zero_tests_and_changed_bytes(self):
        _, captures = completed_captures(self.run, self.manifest)
        self.assertEqual(set(captures), expected_paths())
        self.results["status"] = "failed"
        self.save()
        with self.assertRaisesRegex(VerificationError, "did not pass"):
            completed_captures(self.run, self.manifest)
        self.results["status"] = "passed"
        log = b"test result: ok. 0 passed; 0 failed; 0 ignored;\n"
        (self.run / "command-001.log").write_bytes(log)
        self.results["commands"][1]["log_sha256"] = sha256(log)
        self.save()
        with self.assertRaisesRegex(VerificationError, "exactly once"):
            completed_captures(self.run, self.manifest)
        log = b"test result: ok. 1 passed; 0 failed; 0 ignored;\n"
        (self.run / "command-001.log").write_bytes(log)
        self.results["commands"][1]["log_sha256"] = sha256(log)
        self.save()
        (self.run / self.results["captures"][0]["path"]).write_bytes(b"changed")
        with self.assertRaisesRegex(VerificationError, "bytes or metadata changed"):
            completed_captures(self.run, self.manifest)

    def test_completed_run_rejects_retargeting_and_destination_changes(self):
        changed = copy.deepcopy(self.manifest)
        changed["common"]["commit"] = "0" * 40
        with self.assertRaisesRegex(VerificationError, "different release pins"):
            completed_captures(self.run, changed)
        self.plan["commands"][1]["outputs"][0]["destination"] = "../../outside"
        self.save()
        with self.assertRaisesRegex(VerificationError, "commands differ"):
            completed_captures(self.run, self.manifest)

    def test_installation_updates_whole_artifacts_and_both_pin_files(self):
        plan, captures = completed_captures(self.run, self.manifest)
        release_path = self.repo / MANIFEST.relative_to(REPO)
        release_path.parent.mkdir(parents=True)
        layout = self.repo / "Zcash/Circuits/Fixtures/actionLayout.json"
        layout.parent.mkdir(parents=True)
        layout.write_bytes(b"unchanged layout")
        install_captures(self.repo, self.manifest, plan, captures)
        for relative, data in captures.items():
            self.assertEqual((self.repo / relative).read_bytes(), data)
        updated = json.loads(release_path.read_text())
        self.assertEqual(updated["existing_capture"]["sha256"],
                         sha256(captures[updated["existing_capture"]["path"]]))
        rows = (self.repo / "Zcash/Snark/Fixtures/MANIFEST.tsv").read_text().splitlines()
        rows = [row.split("\t") for row in rows if not row.startswith("#")]
        self.assertEqual({row[0] for row in rows}, expected_paths())
        for path, digest, generator, source, invocation in rows:
            self.assertEqual(digest, sha256(captures[path]))
            self.assertIn("zakura-halo2-proofs 1.2.0", generator)
            self.assertEqual(source, "zakura-core/common@" + self.manifest["common"]["commit"])
            self.assertIn("--exact", invocation)
        self.assertEqual(layout.read_bytes(), b"unchanged layout")
        # Provenance updates do not invalidate a completed run of the same release.
        completed_captures(self.run, updated)

    def test_incomplete_installation_writes_nothing(self):
        plan, captures = completed_captures(self.run, self.manifest)
        before = {path: path.read_bytes() for path in self.repo.rglob("*") if path.is_file()}
        captures.pop(sorted(captures)[0])
        with self.assertRaisesRegex(VerificationError, "incomplete fixture"):
            install_captures(self.repo, self.manifest, plan, captures)
        self.assertEqual(before, {path: path.read_bytes() for path in self.repo.rglob("*") if path.is_file()})

    def test_source_inventory_is_checked_against_the_authenticated_archive(self):
        data = b"released Rust source"
        buffer = io.BytesIO()
        with tarfile.open(fileobj=buffer, mode="w:gz") as archive:
            member = tarfile.TarInfo("common/code.rs")
            member.size = len(data)
            archive.addfile(member, io.BytesIO(data))
        archive_bytes = buffer.getvalue()
        cache = self.root / "cache"
        cache.mkdir()
        (cache / "common.tar.gz").write_bytes(archive_bytes)
        manifest = {"common": {"archive": {"file": "common.tar.gz", "prefix": "common",
                                             "sha256": sha256(archive_bytes)}}}
        plan = {"source_files": {"code.rs": sha256(data)}, "materialized_source_links": {}}
        run = self.root / "source-run"
        source = run / "common/code.rs"
        source.parent.mkdir(parents=True)
        source.write_bytes(data)
        check_run_sources(run, plan, manifest, cache)
        extra = run / "common/build.rs"
        extra.write_bytes(b"unexpected build script")
        with self.assertRaisesRegex(VerificationError, "extra files"):
            check_run_sources(run, plan, manifest, cache)
        extra.unlink()
        source.write_bytes(b"changed source")
        with self.assertRaisesRegex(VerificationError, "source changed"):
            check_run_sources(run, plan, manifest, cache)
        plan["source_files"]["code.rs"] = sha256(source.read_bytes())
        with self.assertRaisesRegex(VerificationError, "inventory differs"):
            check_run_sources(run, plan, manifest, cache)


if __name__ == "__main__":
    unittest.main()
